/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rowgradlesetup;

import java.io.BufferedReader;
import java.io.InputStreamReader;

public class App {

    public static void main(String[] args) {
		BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
		try {
			String originalString = reader.readLine();
			
            System.out.println(originalString);
			
		} catch (Exception e) {
		}
    }
}
